export const TOGGLE_FILTER = 'TOGGLE_FILTER'
export const SEARCH_GUEST = 'SEARCH_GUEST'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const ADD_GUEST = 'ADD_GUEST'
export const REMOVE_GUEST = 'REMOVE_GUEST'
export const UPDATE_GUEST = 'UPDATE_GUEST'
export const EDIT_GUEST = 'EDIT_GUEST'
export const CLEAR_EDIT = 'CLEAR_EDIT'
export const GET_GUESTS= 'GET_GUESTS'
export const GUESTS_ERROR= 'GUESTS_ERROR '
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAIL_REGISTER = 'FAIL_REGISTER'
export const FAIL_LOGIN = 'FAIL_LOGIN '
export const SET_ERROR= 'SET_ERROR '
export const CLEAR_ERROR= 'CLEAR_ERROR '
export const LOG_OUT= 'LOG_OUT '
export const SET_USER= 'SET_USER '
export const AUTH_ERROR= 'AUTH_ERROR '


